- name: "Security"
  description: "Security Tools"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - nmap
    - wireshark-qt
    - sqlmap
    - smbclient
    - evillimiterc
    - crackmapexec
    - john
    - hashcat
    - metasploit
    - airgeddon-git
    - aircrack-ng
